name: deploy latest
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            MY_BASE_DIR="projects"
            MY_CO_DIR="OnlineJSLE"
            if [ -d "$MY_BASE_DIR" ]; then
             cd $MY_BASE_DIR
             cd $MY_CO_DIR --ff-only
             git pull
            else 
              mkdir $MY_BASE_DIR 
              cd $MY_BASE_DIR
              git clone -b latest --single-branch git@github.com:dappelbe/OnlineJSLE.git $MY_CO_DIR
            fi
